#ifndef ESPCOMMUNICATION_H
#define ESPCOMMUNICATION_H

enum Data_Commands {
  OBSERVER_QUERY_POSITION = 20,
  OBSERVER_RESPONSE_POSITION,
  OBSERVER_QUERY_UWB_ADDRESS,
  OBSERVER_RESPONSE_UWB_ADDRESS,
  OBSERVER_ENABLE_UWB,
  OBSERVER_WAKEUP_RECKON,
};


#endif